breeds = [("Bengal",
           "<p>The Bengal is highly active and highly intelligent. This makes him fun to live with, but he can sometimes be challenging. On the whole, the Bengal is a confident, talkative, friendly cat who is always alert. Nothing escapes his notice. He likes to play games, including fetch, and he’s a whiz at learning tricks. His nimble paws are almost as good as hands, and it’s a good thing he doesn’t have opposable thumbs or he would probably rule the world. Bored bengal cats can also adopt some unconventional (and slightly destructive) habits, including: turning light switches on and off, fishing seals out of drains and excitedly plucking CDs from your DVD player.</p>"
           "<p>Fond of playing in water, the Bengal is not above jumping into the tub or strolling into the shower with you. Aquarium and pond fish may be at risk from his clever paws. He also loves to climb and can often be found perching at the highest point he can reach in the home. A tall cat tree or two is a must for this feline, as are puzzle toys that will challenge his intelligence.</p>"
           "<p>On the rare occasions that he isn’t swinging on chandeliers or swimming in your pool, the affectionate Bengal will be pleased to sit on your lap. It goes without saying that he will share your bed. And yes, he steals the covers. (From cattime.com)</p>"),
          ("Bombay",
           "<p>The Bombay is a short-haired breed of domestic cat, closely related to the Burmese. Bombay cats are typically characterized as having an all black coat, black soles, black nose and mouth, with copper or green eyes. The close-lying, sleek and glossy black coat is generally colored to the roots, with little or no paling.</p>"
           "<p>The Bombay has a medium body build that is muscular. Their weight is usually 8 to 15 pounds (3.6 to 6.8 kg) with males typically being heavier than females. (From wikipedia)</p>"),
          ("British Shorthair",
           "<p>The British Shorthair is a relatively powerful-looking large cat, having a broad chest, strong thick-set legs with rounded paws and a medium-length, blunt-tipped tail. The head is relatively large and rounded, with a short muzzle, broad cheeks (most noticeable in mature males, who tend to develop prominent jowls) and large round eyes that are deep coppery orange in the British Blue and otherwise vary in colour depending on the coat. Their large ears are broad and widely set.</p>"
           "<p>The British Blue variant can often be confused with the grey Scottish Fold, a breed closely related to the British Shorthair. However, the Shorthair can be characterised by having its pointy triangle ears, whereas the Fold has softer, folded ears.</p>"
           "<p>They are slow to mature in comparison with most cat breeds, reaching full physical development at approximately three years of age. Unusually among domestic cats they are a noticeably sexually dimorphic breed, with males averaging 9–17 lb (4.1–7.7 kg) and females 7–12 lb (3.2–5.4 kg). (From wikipedia)</p>"),
          ("Calico",
           "<p>Calico cats are domestic cats that are comprised of a garden of cat colors, either vibrant orange (technically known as 'red'), white and black, or more subdued flaxen, blue-gray, and white. In feline genetics, the latter is known as 'dilute calico.' The various patterns of the calico patches are almost as ubiquitous as snowflakes. You'll never see two exactly alike.</p>"
           "<p>Calicoes are almost all female, and the rare male is always sterile. (So much for the hopes of those thinking of breeding a rare line of cats.)</p>"
           "<p>Calicoes are rivaled only by tortoiseshell cats, who are genetically very similar. Indeed, it is often difficult to tell if an individual cat is a calico or a 'tortie with white,' The most common difference is that tortoiseshell colors (red and black) are interwoven throughout the coat, where calico cats have distinctive patches of solid color. Sometimes the distinction is even more blurred, when a calico may have some woven patches intermingled with the solid areas, as depicted in the first photo. Such cats are often called 'calitorts'...or could they be 'torticals?' (From the sprucepets)</p>"),
          ("Dilute Tortoiseshell",
           "<p>The tortoiseshell cat’s coat will be mottled with several patches of blacks, browns, and oranges. They will often have little to no white on their fur but some may have white on their face, their bellies, or their legs. Tortoiseshell markings can appear in just about every breed, with the exception of the breeds that are thought to be Oriental cat breeds.</p>"
           "<p>Dilute tortoiseshell refers to when the coloration of the cat’s coats are much softer colors versus the bright oranges and dark browns or blacks. The colors tend to be softer and almost faded when compared to a regular tortoiseshell coat.</p>"
           "<p>Dilute tortoiseshell cats can be both longhaired and shorthaired, and may even be Maine Coon cats. Maine Coons are well known for their exceptionally long hair.</p>"
           "<p>Because the dilute tortoiseshell markings can appear in just about every domestic cat breed, there are unlikely to be any characteristic unique to dilute tortoiseshells. However, owners of tortoiseshells tend to claim that their cats have much more in the way of an independent and stubborn nature. (From familypet)</p>"),
          ("Himalayan",
           "<p>Like Persians more generally, the Himalayan tends to have a round (cobby) body with short legs, which makes it harder for them to jump as high as other cats do. Since the 1960s, however, some have more of a Siamese-like body,[5] and thus do not have this limitation, but may not be acceptable as show cats, depending on the specific breed standards of the organisation in question.</p>"
           "<p>As with other Persians, there are two types of Himalayans, the traditional or doll-face, and the peke-faced or ultra-typed which has the more extreme squashed-looking facial features. The seal-point Himalayan in the photo to the left is doll-faced while the red(flame)-point in the title image is peke-faced.</p>"
           "<p>Show Himalayans display a nose break as do peke-faced Persians, and have very large, round eyes with the nose leather directly between the eyes. Breeder or pet Himalayans generally have longer noses than the show cats, and may display a longer muzzle and smaller eyes than the show cats do. All three types of cat are Himalayans, however. (from wikipedia)</p>"),
          ("Maine Coon",
           "<p>The Maine Coon is a large and sociable cat, hence its nickname, 'the gentle giant'. It is characterized by a prominent ruff along its chest, robust bone structure, rectangular body shape, an uneven two-layered coat with longer guard hairs over a silky satin undercoat, and a long, bushy tail.</p>"
           "<p>The Maine Coon is a long- or medium-haired cat. The coat is soft and silky, although texture may vary with coat colour. The length is shorter on the head and shoulders and longer on the stomach and flanks, with some cats having a lion-like ruff around their neck. Minimal grooming is required for the breed compared to other long-haired breeds, as their coat is mostly self-maintaining owing to a light-density undercoat. The coat is subject to seasonal variation, with the fur being thicker in the winter and thinner during the summer.</p>"
           "<p>Maine Coons can have any colours that other cats have. Colours indicating crossbreeding, such as chocolate, lavender, the Siamese pointed patterns or the 'ticked' patterns, are not accepted by some breed standards (the ticked pattern, for example, is accepted by TICA and CFA). The most common pattern seen in the breed is brown tabby. All eye colours are accepted under breed standards, with the exception of blue or odd-eyes (i.e. heterochromia iridium, or two eyes of different colours) in cats possessing coat colours other than white. (From wikipedia)</p>"),
          ("Persian",
           "<p>The Persian has a distinctive appearance: a large, round head; large, round eyes; a short nose; full cheeks; and small ears with rounded tips. The head is supported by a short, thick neck and a deceptively sturdy, muscular body—a type known as “cobby.” A Persian’s legs are short, thick and strong with large, round, firm paws. The tail is short but proportional to the length of the cat’s body.</p>"
           "<p>A long, thick, shiny coat with a fine texture completes the Persian’s look. It’s long all over the body and includes an immense ruff around the neck, a deep frill between the front legs, long ear and toe tufts, and a full “brush,” or tail.</p>"
           "<p>Persians can come in different “looks.” Some, known as Peke-face Persians, have an extremely flat face. Think twice about the breathing problems such a cat might have before deciding to get one. “Doll-face” Persians are said to have a more old-fashioned appearance, with a face that is not as flat as the show Persian or the Peke-face Persian.</p>"
           "<p>Persians of all stripes stand out for their infinite variety of coat colors and patterns. Imagine, if you will, seven solid color divisions—white, blue, black, red, cream, chocolate and lilac—plus silver and golden division colors of chinchilla and shaded silver or golden and blue chinchilla and blue shaded silver or golden; and then there are the shaded, smoke, tabby, calico, particolor and bicolor divisions. That’s not counting the various pointed patterns of the Himalayan. Eye color is related to coat color. For instance, white Persians have deep blue or brilliant copper eyes; other solid-colored Persians have brilliant copper eyes; silver and golden Persians have green or blue-green eyes; and so on. (From cattime)</p>"),
          ("Siamese",
           "<p>The breed standard of the modern Siamese calls for an elongated, tubular, and muscular body and a triangular head, forming a perfect triangle from the tip of the nose to each tip of the ear. The eyes are almond-shaped and light blue, while the ears are large, wide-based, and positioned more towards the side of the head. The breed has a long neck, a slender tail, and fur that is short, glossy, fine, and adheres to the body with no undercoat. Its pointed color scheme and blue eyes distinguish it from the closely related Oriental Shorthair. The modern Siamese shares the pointed color pattern with the Thai, or traditional Siamese, but they differ in head and body type.</p>"
           "</p>The pointed pattern is a form of partial albinism, resulting from a mutation in tyrosinase, an enzyme involved in melanin production. The mutated tyrosinase enzyme is heat-sensitive; it fails to work at normal body temperatures, but becomes active in cooler (< 33 °C) areas of the skin. This results in dark colouration in the coolest parts of the cat's body, including the extremities and the face, which is cooled by the passage of air through the sinuses. All Siamese kittens, although pure cream or white at birth, develop visible points in the first few months of life in colder parts of their body. By the time a kitten is four weeks old, the points should be sufficiently "
           "clearly distinguishable to recognise which colour they are. Siamese cats tend to darken with age, and generally, adult Siamese living in warm climates have lighter coats than those in cool climates. Originally the vast majority of Siamese had seal (extremely dark brown, almost black) points, but occasionally Siamese were born with 'blue' (a cool grey) points, genetically a dilution of seal point; chocolate (lighter brown) points, a genetic variation of seal point; or lilac (pale warm gray) points, genetically a diluted chocolate. These colours were at first considered 'inferior' seal points, and were not qualified for showing or breeding. (From wikipedia)</p>"),
          ("Torbie",
           "<p>Like Torbie cats, Tortie cats also belong to the tricolor breed. Nevertheless, they generally 80% look like the Torbie. Features that disgust these two breeds are their colors and patterns on the coat.</p>"
           "<p>Although both belong to the tricolor breed, Tortie cats have only two colors – orange and black. Sometimes, there are few of very little white points on the fur. However, they’re too small for you to see them and only 10% of Tortie have this.</p>"
           "<p>Moreover, on Tortie’s coat, there is no pattern. They may have patches from small to large size, depending on each individual. However, in general, most of them have a fur that looks like a mess with two colors with no certain shape and not in order. You may feel like they are wearing a patchy cloth.</p>"
           "<p>So, the best way to distinguish them: Torbie cats have 3 colors and patterns on their coat, while Tortie cats only have 2 colors with no extra patterns. (From petful101)</p>"),
          ("Tortoiseshell",
           "<p>Tortoiseshell cats have particolored coats with patches of various shades of red and black, and sometimes white. The size of the patches can vary from a fine speckled pattern to large areas of color. Typically, the more white a cat has, the more solid the patches of color. Dilution genes may modify the coloring, lightening the fur to a mix of cream and blue, lilac or fawn; the markings on tortoiseshell cats are usually asymmetrical.</p>"
           "<p>Occasionally tabby patterns of black and brown (eumelanistic) and red (phaeomelanistic) colors are also seen. These patched tabbies are often called a tortie-tabby, a torbie or, with large white areas, a caliby. Not uncommonly there will be a 'split face' pattern with black on one side of the face and orange on the other, with a dividing line running down the bridge of the nose. Tortoiseshell coloring can also be expressed in the point pattern, referred to as a tortie point. (From wikipedia)</p>"),
          ("Toyger",
           "<p>The Toyger was developed so their coats resembled that of a wild tiger. They boast having the Bengal in their lineage although they are very different looking cats. They are medium to large in size and have lithe, well-muscled and low slung bodies which gives them their sleek appearance. Females tend to be that much lighter and smaller than their male counterparts, but both have long, broad, medium sized, wedge shaped heads that are nicely in proportion to their bodies. Muzzles are strong and look very similar to an inverted heart with cats having well-defined, prominent whisker pads. Ears are small, nicely rounded and set well apart on a cat's head. Cats have thick furring on their temples and ears but no tufts on their ears.</p>"
           "<p>The Toyger has small to medium sized, round eyes with a little hooding and which slant towards the base of a cat's ears. They always have a kind, serious look about their eyes. Seen in profile, cats have a nice angle at their foreheads with the line to the bridge of the nose being virtually straight, with just a hint of a concave curve. Noses are long and nicely rounded having a muscular look about them. Chins are deep and wide being strong and prominent. (From pets4homes)</p>"),
          ("Tuxedo",
           "<p>Tuxedo cats have a prominent bicolor pattern. Their appeal comes from the stark black-and-white contrast of their coat combined with the pattern, which is reminiscent of formal wear for men. Any combination of the black-and-white pattern qualifies as a tuxedo, but generally, the body is black and the chest and paws are white. Other bicolor cats are not commonly called tuxedo cats and they may be red (orange) and white or blue (gray) and white. Because the term isn't strictly defined, you are free to call your bicolor gray-and-white cat a tuxedo if it exhibits this pattern.</p>"
           "<p>Tuxedo is a coloration pattern can occur in many different cat breeds. The bicolor pattern is noted in the breed standards for the American shorthair, British Shorthair, Maine coon, Manx, Norwegian Forest Cat, Scottish fold, Turkish Angora, and Turkish Van. It is not allowed in some breed standards.</p>"
           "<p>The tuxedo pattern is named after the attire human men wear for formal occasions. Nothing is so dramatic as seeing a 'tuxie,' as it is affectionately called, dressed in its best bib and tucker. Some tuxies also wear 'spats,' or white boots. Tuxedo cats are truly the gentlemen of cat color patterns. Female tuxedo cats are just as common as there is no gender conflict here. (From the sprucepets)</p>")]
