breeds = [("Bengal",
           "The Bengal cat is a domesticated cat breed created from hybrids of domestic cats, especially the spotted Egyptian Mau, with the Asian leopard cat (Prionailurus bengalensis). The breed name comes from the leopard cat's taxonomic name."),
          ("Bombay",
           "The Bombay cat is a type of short-haired cat developed by breeding sable Burmese and black American Shorthair cats, to produce a cat of mostly Burmese type, but with a sleek, panther-like black coat. Bombay is the name given to black cats of the Asian group."),
          ("British Shorthair",
           "The British Shorthair is the pedigreed version of the traditional British domestic cat, with a distinctively stocky body, dense coat, and broad face. The most familiar colour variant is the 'British Blue', with a solid grey-blue coat, orange eyes, and a medium-sized tail."),
          ("Calico",
           "A calico cat is a domestic cat of any breed with a tri-color coat. The calico cat is most commonly thought of as being typically 25% to 75% white with large orange and black patches (or sometimes cream and grey patches)."),
          ("Dilute Tortoiseshell",
           "Dilute tortie cats have a tortoiseshell coat pattern with one remarkable difference: instead of the striking, dark mix of orange and black, dilute tortoiseshell cats have a muted, almost blue and yellow color."),
          ("Himalayan",
           "The Himalayan, is a breed or sub-breed of long-haired cat similar in type to the Persian, with the exception of its blue eyes and its point colouration, which were derived from crossing the Persian with the Siamese."),
          ("Maine Coon",
           "The Maine Coon is a large domesticated cat breed. It has a distinctive physical appearance and valuable hunting skills. It is one of the oldest natural breeds in North America, specifically native to the US state of Maine,[3] where it is the official state cat."),
          ("Persian",
           "The Persian cat is a long-haired breed of cat characterized by its round face and short muzzle. It is also known as the 'Persian Longhair' in the English-speaking countries."),
          ("Siamese",
           "The Siamese cat is one of the first distinctly recognized breeds of Asian cat. Derived from the Wichianmat landrace, one of several varieties of cat native to Thailand (formerly known as Siam), the original Siamese became one of the most popular breeds in Europe and North America in the 19th century."),
          ("Torbie",
           "The tabby cat may have a 'split face' appearance with orange/brown on one side and black on another side of the face, divided by a line running down along the bridge of the nose."),
          ("Tortoiseshell",
           "Tortoiseshell is a cat coat coloring named for its similarity to tortoiseshell material. Like calicos, tortoiseshell cats are almost exclusively female. Male tortoiseshells are rare and are usually sterile."),
          ("Toyger",
           "The toyger is a breed of domestic cat, the result of breeding domestic shorthaired tabbies (beginning in the 1980s) to make them resemble a 'toy tiger', as its striped coat is reminiscent of the tiger's."),
          ("Tuxedo",
           "A tuxedo cat, or Felix cat, or Julius cat is a bicolor cat with a white and black coat. They are called 'tuxedo' cats because they appear to be wearing the type of black tie formal wear commonly known in the United States and Canada as a tuxedo.")]
